language: php

php:
- '7.0'
- '5.6'

env:
  matrix:
    - WP_VERSION=nightly WP_THEME=twentyseventeen
    - WP_VERSION=latest WP_THEME=twentysixteen

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - composer install
  - npm install
  - npm run install-wp
  - npm run wp >/dev/null 2>&1 &

script:
  - npm test
